### PR TITLE
Add support for custom output directory

### PR DESCRIPTION
**Pull request by handcraftedbits**
Outputting the flymd files in the same directory as the Markdown file being edited has two issues:

* It can potentially leave behind artifacts that you don't intend to be part of your source control.
* When using [TRAMP](https://www.emacswiki.org/emacs/TrampMode), the local browser won't be able to open flymd.html since the path to a local file isn't returned.

To fix this, I added the `flymd-output-directory` variable.  If `nil`, the current behavior is preserved.  Otherwise, files will be saved in `<flymd-output-directory>/<fixed-buffer-directory>/flyd.[md|html]`, where `<fixed-buffer-directory>` is the directory associated with the buffer with [Windows reserved characters](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) replaced with underscores.  This allows TRAMP path names to work correctly under Windows.

### CODE REVIEW

**Comment by mola-T** [comment]
Thanks. Would you do me a a favour to modify the function `flymd-get-output-directory`:

```elsip
    (defun flymd-get-output-directory (buffer)
      "Gets the correct output directory for flymd preview files."
      (if flymd-output-directory
          (let ((output-dir (file-name-as-directory
                             (concat (file-name-as-directory flymd-output-directory)
                                     (secure-hash 'md5 (buffer-file-name buffer))))))
            (make-directory output-dir t)
            output-dir)
        (file-name-directory (buffer-file-name buffer))))
```

I make two changes

1. `output-dir` is a free-variable. So put it in `let`.
2. The way you generate the file path produce a very complicated folder structure. I suggest hashing it instead. It not only resolves all unwanted characters, it turns the path to a single folder.

**Comment by handcraftedbits** [comment]
Good suggestions, thanks!  Just committed the changes.

**Comment by mola-T** [comment]
Thanks. Please remove the file `#flymd.el#`.

**Comment by handcraftedbits** [comment]
Sorry about that, fixed.  Thanks again.

**Comment by mola-T** [comment]
Thanks and merged.

**Pull request merged**
